homeassistant:
  # Name of the location where Home Assistant is running
  name: Arglam Wood
  # Location required to calculate the time the sun rises and sets
  latitude: 0
  longitude: 0
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: GMT
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction: 

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#   base_url: arglamwood.duckdns.org:8123
#   ssl_certificate: /home/homeassistant/dehydrated/certs/arglamwood.duckdns.org/fullchain.pem
#   ssl_key: /home/homeassistant/dehydrated/certs/arglamwood.duckdns.org/privkey.pem
#   base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

recorder:
  db_url: sqlite:///opt/homeassistant/home-assistant_v2.db

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  - platform: onewire
    names:
      28-021313d1a9aa: bathroom #1
      28-021312cb82aa: office #2
      28-01131b7f1a66: bedroom #3
      28-021312cf9caa: living_room #4
      28-01131b81aed5: kitchen #5
# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
switch:
  - platform: rpi_gpio
    ports:
      2: Bathroom
      3: Office
      4: Bedroom
      17: Living Room
      27: Kitchen
      22: Pump
      10: Bio_hotwater
      9: Elec_hotwater
    invert_logic: true

climate:
  - platform: generic_thermostat
    name: Thermostat Living room
    heater: switch.living_room
    target_sensor: sensor.living_room_temperature
    min_temp: 15
    max_temp: 27
    ac_mode: False
    target_temp: 21
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 360
    keep_alive:
      minutes: 3
    initial_operation_mode: "auto"
    away_temp: 8

  - platform: generic_thermostat
    name: Thermostat Kitchen
    heater: switch.kitchen
    target_sensor: sensor.kitchen_temperature
    min_temp: 15
    max_temp: 27
    ac_mode: False
    target_temp: 21
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
      seconds: 360
    keep_alive:
      minutes: 3
    initial_operation_mode: "auto"
    away_temp: 8


binary_sensor:
  - platform: template
    sensors:
      bathroom:
        value_template: "{{ is_state('switch.bathroom', 'on') }}"
      office:
        value_template: "{{ is_state('switch.office', 'on') }}"
      bedroom:
        value_template: "{{ is_state('switch.bedroom', 'on') }}"
      living_room:
        value_template: "{{ is_state('switch.living_room', 'on') }}"
      kitchen:
        value_template: "{{ is_state('switch.kitchen', 'on') }}"
      morning:
        value_template: "{{ is_state('automation.heating_evenings_on', 'on') }}"
      evening:
        value_template: "{{ is_state('automation.heating_evenings_off', 'on') }}"

  - platform: workday
    country: UK
    workdays: [mon, tue, wed, thu, fri]

media_player:
  - platform: squeezebox
    host: 192.168.1.9

input_boolean:
  heating_home_today:
    name: Home Today
    initial: off

  heating_away_mode:
    name: Heating Away Mode
    initial: off

input_datetime:
  heating_away_mode_runtime: 
    name: heating_away_mode_runtime 
    has_date: true
    has_time: true
