- alias: Keep Pump on
  trigger:
    - platform: state
      entity_id: group.underfloor
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.pump

- alias: Pump off
  trigger:
    - platform: state
      entity_id: group.underfloor
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.pump
 
- alias: rooms off if pump off
  trigger:
    - platform: state
      entity_id: switch.pump
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: group.underfloor


- alias: Heating Morning On
  trigger:
    - platform: time
      at: '05:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.bathroom
    - service: switch.turn_on
      entity_id: switch.office
    - service: switch.turn_on
      entity_id: switch.bedroom
    - service: climate.turn_on
      entity_id: climate.thermostat_kitchen
    - service: climate.turn_on
      entity_id: climate.thermostat_living_room


- alias: Heating Morning Off
  trigger:
    - platform: time
      at: '8:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.heating_home_today
      state: 'off'
  action:
    - service: switch.turn_off
      entity_id: group.underfloor
    - service: climate.turn_off
      entity_id: group.underfloor
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_home_today

- alias: Heating Evenings On
  trigger:
    - platform: time
      at: '15:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.bathroom
    - service: climate.turn_on
      entity_id: climate.thermostat_living_room
    - service: climate.turn_on
      entity_id: climate.thermostat_kitchen
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_home_today


- alias: Heating Evenings Off
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom
    - service: climate.turn_off
      entity_id: climate.thermostat_living_room
    - service: climate.turn_off
      entity_id: climate.thermostat_kitchen
    - service: input_boolean.turn_off
      entity_id: input_boolean.heating_home_today

#- alias: Thermostat_living_room 
#  trigger:
#    - platform: numeric_state
#      entity_id: sensor.living_room_temperature
#      above: '20'
#  action:
#    - service: switch.turn_off
#      entity_id: switch.living_room


- alias: Heating Home Today weekday
  trigger:
    - platform: state
      to: 'on'
      entity_id: input_boolean.heating_home_today
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
    - service: switch.turn_off
      entity_id: group.underfloor
    - service: climate.turn_off
      entity_id: group.underfloor
    - service: climate.turn_on
      entity_id: climate.thermostat_kitchen
    - service: switch.turn_on
      entity_id: switch.office
    - service: switch.turn_on
      entity_id: switch.bathroom


- alias: Heating Home Today weekend
  trigger:
    - platform: state
      to: 'on'
      entity_id: input_boolean.heating_home_today
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'off'
  action:
    - service: switch.turn_off
      entity_id: group.underfloor
    - service: climate.turn_off
      entity_id: group.underfloor
    - service: climate.turn_on
      entity_id: climate.thermostat_kitchen
    - service: climate.turn_on
      entity_id: climate.thermostat_living_room
    - service: switch.turn_on
      entity_id: switch.bathroom

- alias: Heating Home Today off
  trigger:
    - platform: state
      to: 'off'
      entity_id: input_boolean.heating_home_today
  action:
    - service: switch.turn_off
      entity_id: group.underfloor
    - service: climate.turn_off
      entity_id: group.underfloor

- alias: Heating Away Mode
  trigger:
    - platform: state
      entity_id: input_boolean.heating_away_mode
      to: 'on'
  action:
    - service: input_datetime.set_datetime
      data_template:
        entity_id: input_datetime.heating_away_mode_runtime
        time: '{{ (as_timestamp(now()) | timestamp_custom("%H:%M:%S", true)) }}'
        date: '{{ (as_timestamp(now()) | timestamp_custom("%Y-%m-%d", true)) }}'


#heating_away_mode_runtime

- alias: Away Mode Switch  
  trigger:
    - platform: state
      to: 'on'
      entity_id: input_boolean.heating_away_mode
  action:
    - service: switch.turn_on
      entity_id: switch.bathroom
    - service: climate.set_away_mode
      data_template:
        entity_id: climate.thermostat_kitchen
        away_mode: 'on'





#- alias: "Away Mode Switch"
#  trigger:
#    - platform: state
#      to: 'on'
#      entity_id: input_boolean.heating_away_mode
#  action:
#    - service: climate.set_away_mode
#      data_template:
#        entity_id: climate.termostat_kitchen
#        away_mode: 'on'
#    - service: switch.turn_on
#      entity_id: switch.bathroom

#        away_mode: >
#          {% if is_state('input_boolean.heating_away_mode', 'on') %}
#            on
#          {% else %}
#            off
#          {% endif %}
#      data:
#       entity_id: climate.termostat_kitchen
