- alias: Keep Pump on
  trigger:
    - platform: state
      entity_id: group.underfloor
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.pump

- alias: Pump off
  trigger:
    - platform: state
      entity_id: group.underfloor
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.pump
  
- alias: rooms off if pump off
  trigger:
    - platform: state
      entity_id: switch.pump
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: group.underfloor


- alias: Heating - Morning On
  trigger:
    - platform: time
      at: '05:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.bathroom
    - service: switch.turn_on
      entity_id: switch.office
    - service: switch.turn_on
      entity_id: switch.bedroom

- alias: Heating - Morning Off
  trigger:
    - platform: time
      at: '8:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom
    - service: switch.turn_off
      entity_id: switch.office
    - service: switch.turn_off
      entity_id: switch.bedroom

- alias: Heating - Evenings On
  trigger:
    - platform: time
      at: '15:30:00'
  action:
    - service: switch.turn_on
      entity_id: switch.bathroom
    - service: switch.turn_on
      entity_id: switch.living_room
    - service: switch.turn_on
      entity_id: switch.kitchen

- alias: Heating - Evenings Off
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom
    - service: switch.turn_off
      entity_id: switch.living_room
    - service: switch.turn_off
      entity_id: switch.kitchen

